# Setup
name:         Dave's Cloud Thoughts
tagline:      Ramblings and discussions from a Cloud Solutions Architect
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown